### ISSUE TITLE
git merde

### ISSUE THREAD

**Issue by GaloisGirl** [Xaxetrov/git-typo#12]
I apologize for the profanity, but I did make that unfortunate typo a couple of times.

**Comment by Xaxetrov** [comment]
Oh indeed. I do not have a keyboard where these two keys are close though. Is it on a specific one or do you slip two keys at once on Qwerty ?
Edit: If you have an idea for the output ? I do not have one so if it was me I would do the same as "git stash poop" for now 'https://github.com/Xaxetrov/git-typo/blob/master/shellGitTypo.sh#L81)
