### ISSUE TITLE
git pill

### ISSUE THREAD

**Issue by Xaxetrov** [Xaxetrov/git-typo#21]
Idea: Something about medicine.

**Comment by Kardelio** [comment]
Ill grab this one if thats ok?

**Comment by Kardelio** [comment]
Pull request #22 is ready, please let me know if there are any issues :D

**Comment by Xaxetrov** [comment]
OK thanks ! I'll have a look at it as soon as possible.

**Comment by Kardelio** [comment]
@Xaxetrov this is done and merged, I appreciate all your feedback and its been really interesting too, always something to learn, just wondering if there is anything else that you might want someone to help with or do? Im bored atm and wondering if there is anything more I can do to be useful?

**Comment by Xaxetrov** [comment]
Yeah you can pick any issue, most are quite easy !

**Comment by Xaxetrov** [comment]
Mplemented in https://github.com/Xaxetrov/git-typo/pull/22
